### ISSUE TITLE
Prefetched tarballs no longer have any effect

### ISSUE THREAD

**Issue by zupo** [teamniteo/nix-docker-base#13]
It seems that Nix downloads the pinned tarball even if the same tarball already comes with the Docker image.

Below is a log excerpt from CircleCI.

First step is to pull the specified Docker image. Here I pulled `nixos-21.05:1f91fd1040667e9265a760b0347f8bc416249da7`.

```
Starting container niteo/nixpkgs-nixos-21.05:1f91fd1040667e9265a760b0347f8bc416249da7
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image cache not found on this host, downloading niteo/nixpkgs-nixos-21.05:1f91fd1040667e9265a760b0347f8bc416249da7
1f91fd1040667e9265a760b0347f8bc416249da7: Pulling from niteo/nixpkgs-nixos-21.05

niteo/nixpkgs-nixos-21.05:1f91fd1040667e9265a760b0347f8bc416249da7:=====>]  136.9MB/136.9MBB
  using image niteo/nixpkgs-nixos-21.05@sha256:25008ab4401037a3f51eefe9aaac535e9f07f44f723fee9178f0c1f6378c6132
  pull stats: download 130MiB in 1.544s (84.22MiB/s), extract 130MiB in 8.155s (15.94MiB/s)
  time to create container: 72ms
Digest: sha256:25008ab4401037a3f51eefe9aaac535e9f07f44f723fee9178f0c1f6378c6132
Status: Downloaded newer image for niteo/nixpkgs-nixos-21.05:1f91fd1040667e9265a760b0347f8bc416249da7
Time to upload agent and config: 1.180070393s
Time to start containers: 1.074425303s
```

Then I run nix-shell which is pinned like this:

```
    "nixpkgs": {
        "branch": "21.05",
        "description": "Nix Packages collection",
        "homepage": null,
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "1f91fd1040667e9265a760b0347f8bc416249da7",
        "sha256": "1lcfcwgal9fpaiq71981abyzz160r6nx1y4pyy1dnvaf951xkdcj",
        "type": "tarball",
        "url": "https://github.com/nixos/nixpkgs/archive/1f91fd1040667e9265a760b0347f8bc416249da7.tar.gz",
        "url_template": "https://github.com/<owner>/<repo>/archive/<rev>.tar.gz"
    },
```

One of the first lines of output show me that nix still fetches the tarball, instead of using the one that comes prefetched in the image:

```
nix-shell --run "echo 'nix-shell successfully entered'"

Written to /root/.config/cachix/cachix.dhall
Configured private read access credentials in /etc/nix/netrc
Configured https://scrooge.cachix.org binary cache in /etc/nix/nix.conf
unpacking 'https://github.com/nixos/nixpkgs/archive/1f91fd1040667e9265a760b0347f8bc416249da7.tar.gz'...
...
```

**Comment by zupo** [comment]
@Infinisil: any chance you could take a look at this or should I find someone else?

**Comment by infinisil** [comment]
Did you check this from the readme?

> Finally, use the following command to check the tarballs name. It needs to end with `nixpkgs-src` for the prefetched nixpkgs to apply:
>
>     nix-instantiate --eval -E '(import nix/sources.nix).nixpkgs.outPath
>     => "/nix/store/r07cldfsnr8kvkr1kpsc6jf6bibfc1mg-nixpkgs-src"

**Comment by infinisil** [comment]
In the image I can see that the store path matches between what is in the store already and what the fetch should give:
```
bash-4.4# ls /nix/store | grep nixpkgs
lwiwwd0ppkj8lasfllywy3zn6rspm8nc-nixpkgs-src
bash-4.4# nix-instantiate --eval -E 'fetchTarball { name = "nixpkgs-src"; url = "https://github.com/nixos/nixpkgs/archive/1f91fd1040667e9265a760b0347f8bc416249da7.tar.gz"; sha256 = "1lcfcwgal9fpaiq71981abyzz160r6nx1y4pyy1dnvaf951xkdcj"; }'
"/nix/store/lwiwwd0ppkj8lasfllywy3zn6rspm8nc-nixpkgs-src"
```

**Comment by zupo** [comment]
So it should work, right?

**Comment by infinisil** [comment]
The path from the command I showed needs to match, can you confirm that it gives the same path in the repository as the one above?

If it matches then I believe the problem comes from another nixpkgs being fetched from somewhere else, not from niv directly. You can probably grep for the `1f91fd1040667e9265a760b0347f8bc416249da7` hash it's downloading to figure out where it comes from.

**Comment by zupo** [comment]
Sorry for misunderstanding, let me look again.

**Comment by zupo** [comment]
Works like a charm, I just had to follow the documentation 🤦. Thanks for the handholding, and sorry for the noise :(

**Comment by infinisil** [comment]
No worries!
